version: "3"

volumes:
  vol-emqx-data:
  vol-emqx-etc:
  vol-emqx-log:
  vol-influxdb-lib:
  
networks:
  default:
  
services:
  emqx:
    image: emqx/emqx:v4.1.3
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    ports:
      - 1883:1883
      - 18083:18083
      - 8081:8081
    environment:
      - EMQX_NAME=emqx
      - EMQX_LOADED_PLUGINS=emqx_recon,emqx_retainer,emqx_management,emqx_dashboard
    networks:
      - default
    restart: always

  nodered:
    image: pi_node-red:latest
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    environment:
      - TZ=Asia/Hong_Kong
    ports:
      - 1880:1880
    volumes:
      - /home/$USER/nodered:/data
    networks:
      - default
    restart: always
    
  influxdb:
    image: influxdb:1.8.1
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=${DB_NAME}
    volumes:
      - vol-influxdb-lib:/var/lib/influxdb
    networks:
      - default
    restart: always
    
  grafana:
    image: grafana/grafana:7.1.3
    ports:
      - 3000:3000
    networks:
      - default
    restart: always
